project:
  type: website
  resources:
    - googlec569129479a87143.html
    - robots.txt

website:
  title: "Roxana Rodriguez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: digital-marketing.qmd
        text: Digital Marketing
      - href: marketing-analytics.qmd
        text: Marketing Analytics
      - href: resume.qmd
        text: Resume

metadata:
  description: "Digital Marketing portfolio featuring website design, and data visualization projects"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true
    include-in-header: includes/gtm-head.html
    include-before-body: includes/gtm-body.html

