---
title: "résumé "
---

You can view a PDF version of my résumé [here](resume/resume.pdf)

## Education

| Degree | Year | Institution |
|------------------------|------------------------|-------------------------|
| M.S. Digital Marketing and Analytics | August 2026 | California Polytechnic University, Pomona |
| B.A. Psychology | December 2019 | California State University, Northridge |

## Experience

**AltaMed,** Data Management Coordinator

*\[2025 - Present\]*

-   Entered and managed community health assessment data to ensure accuracy and readiness for analysis.

-   Performed data cleaning and transformation to standardize datasets, resolve inconsistencies, and improve overall data quality.

-   Analyzed outreach and assessment data to identify trends, patterns, and insights related to community health needs and program effectiveness.

-   Developed data visualizations and summary reports to communicate key findings to internal teams and support decision-making.

**Roxana Rodriguez,** Freelance Graphic Designer

*\[2022 - Present\]*

-   Designed and developed SEO-optimized websites that increased organic traffic, user engagement, and conversion rates.

-   Built strategic brand identities aligned with target audiences to enhance brand awareness and market positioning.

-   Collaborated with clients to translate marketing goals into data-driven design solutions that support campaign performance.

-   Created digital and print marketing materials, including social media assets and promotional content to drive audience engagement and brand consistency across marketing channels.

## SKILLS

**Skills:** R programming, SQL, Tableau, Google Analytics, Google Ads, SEO, Adobe Illustrator, Adobe Photoshop, Adobe InDesign, Figma, WordPress.

**Languages:** English, Spanish.

## Certifications

**Glendale Community College**

Graphic Design Certificate, *December 2022.*

**Google**

Google Analytics Certificate, *February 2026.*

**HubSpot**

Email Marketing Certificate, *October 2024.*

**Google**

UX Design Certificate, *September 2022.*
